let partners=JSON.parse(localStorage.getItem('mohteref_partners')||'[]'),active=null;
const $=id=>document.getElementById(id);
function toggleMenu(force){let s=$('sidebar'),ov=$('overlay');if(!s)return;let o=force===undefined?!s.classList.contains('open'):force;s.classList.toggle('open',o);if(ov)ov.classList.toggle('show',o)}
function esc(s){return String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function save(){localStorage.setItem('mohteref_partners',JSON.stringify(partners));render()}
function addPartner(){let n=$('name').value.trim(),e=$('email').value.trim(),p=$('phone').value.trim();if(!n){alert('أدخل اسم الشركة أو الجهة');return}if(!e&&!p){alert('أدخل البريد الإلكتروني أو رقم التواصل على الأقل');return}partners.unshift({id:Date.now(),name:n,email:e,phone:p,type:$('type').value.trim(),status:'لم يتم التواصل',notes:$('notes').value.trim(),createdAt:new Date().toISOString()});localStorage.setItem('mohteref_partners',JSON.stringify(partners));alert('تمت إضافة الشركة إلى قائمة لم يتم التواصل معهم');location.href='not-contacted.html'}
function render(){if($('total')){$('total').textContent=partners.length;$('contacted').textContent=partners.filter(x=>x.status!=='لم يتم التواصل').length;$('notContacted').textContent=partners.filter(x=>x.status==='لم يتم التواصل').length;$('done').textContent=partners.filter(x=>x.status==='شراكة مكتملة').length}if(!$('cards'))return;let q=($('search')?.value||'').trim().toLowerCase(),a=partners.filter(x=>[x.name,x.email,x.phone,x.type,x.status].join(' ').toLowerCase().includes(q));let f=document.body.dataset.filter||'all';if(f==='contacted')a=a.filter(x=>x.status!=='لم يتم التواصل');if(f==='not-contacted')a=a.filter(x=>x.status==='لم يتم التواصل');$('cards').innerHTML=a.length?a.map(x=>`<article class="partner"><div class="partner-top"><div><div class="meta">${esc(x.type||'جهة شراكة')}</div><h3>${esc(x.name)}</h3></div><div class="icon">▦</div></div><div class="meta">${esc(x.email||'لا يوجد بريد')}<br>${esc(x.phone||'لا يوجد رقم')}</div><span class="badge">${esc(x.status)}</span>${x.notes?`<div class="meta" style="margin-top:10px">${esc(x.notes)}</div>`:''}<div class="actions">${x.status==='لم يتم التواصل'?`<button class="btn btn-main" onclick="contactPartner(${x.id})">تواصل</button>`:`<button class="btn btn-soft" disabled>تم التواصل</button>`}<button class="btn btn-danger" onclick="removePartner(${x.id})">حذف</button></div></article>`).join(''):'<div class="empty">لا توجد بيانات في هذه الصفحة.</div>'}
function contactPartner(id){active=partners.find(x=>x.id===id);if(!active)return;$('targetName').textContent=active.name;$('to').value=active.email||'لا يوجد بريد إلكتروني مسجل';$('subject').value='مقترح شراكة وتعاون مع مركز محترف';$('body').value=`السلام عليكم ورحمة الله وبركاته،\n\nنسعد في مركز محترف بالتواصل معكم لبحث فرص الشراكة والتعاون المشترك.\n\nوتفضلوا بقبول خالص التحية والتقدير.\nمركز محترف`;$('sendStatus').textContent=active.email?'اكتب الموضوع والرسالة، وبعد التواصل اضغط تم التواصل.':`رقم التواصل: ${active.phone||'غير مسجل'} — بعد إتمام التواصل اضغط تم التواصل.`;$('mailModal').classList.add('show')}
function markContacted(){if(!active)return;active.status='تم التواصل';active.contactedAt=new Date().toISOString();localStorage.setItem('mohteref_partners',JSON.stringify(partners));closeMail();render();if(document.body.dataset.filter==='not-contacted')alert('تم نقل الشركة إلى صفحة تم التواصل معهم')}
function removePartner(id){if(confirm('هل تريد حذف هذه الجهة؟')){partners=partners.filter(x=>x.id!==id);save()}}
function closeMail(){$('mailModal').classList.remove('show')}function prepareSend(){if(!$('subject').value.trim()||!$('body').value.trim()){$('sendStatus').className='status warn';$('sendStatus').textContent='اكتب الموضوع والرسالة أولاً.';return}$('sendStatus').className='status warn';$('sendStatus').textContent='جاهز للإرسال؛ يتبقى ربط Gmail API لتفعيل الإرسال المباشر.'}function copyMessage(){navigator.clipboard.writeText(`إلى: ${$('to').value}\nالموضوع: ${$('subject').value}\n\n${$('body').value}`);$('sendStatus').className='status ok';$('sendStatus').textContent='تم نسخ الرسالة.'}
document.addEventListener('DOMContentLoaded',render);