let partners=JSON.parse(localStorage.getItem('mohteref_partners')||'[]'),active=null;const $=id=>document.getElementById(id);const nowISO=()=>new Date().toISOString();
function toggleMenu(force){let s=$('sidebar'),ov=$('overlay');if(!s)return;let o=force===undefined?!s.classList.contains('open'):force;s.classList.toggle('open',o);if(ov)ov.classList.toggle('show',o)}
function esc(s){return String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function persist(){localStorage.setItem('mohteref_partners',JSON.stringify(partners))} function save(){persist();render()}
function hist(x,type,text){x.history=x.history||[];x.history.unshift({at:nowISO(),type,text})}
function addPartner(){let n=$('name').value.trim(),e=$('email').value.trim(),p=$('phone').value.trim();if(!n)return alert('أدخل اسم الشركة أو الجهة');if(!e&&!p)return alert('أدخل البريد الإلكتروني أو رقم التواصل على الأقل');let x={id:Date.now(),name:n,email:e,phone:p,type:$('type').value.trim(),status:'لم يتم التواصل',notes:$('notes').value.trim(),createdAt:nowISO(),history:[]};hist(x,'إضافة','تمت إضافة الجهة للنظام');partners.unshift(x);persist();location.href='not-contacted.html'}
function counts(){return {total:partners.length,not:partners.filter(x=>x.status==='لم يتم التواصل').length,waiting:partners.filter(x=>x.status==='بانتظار الرد').length,replied:partners.filter(x=>x.status==='تم الرد').length,done:partners.filter(x=>x.status==='تم الاتفاق').length,uninterested:partners.filter(x=>x.status==='غير مهتم').length}}
function render(){let c=counts();[['total',c.total],['notContacted',c.not],['waiting',c.waiting],['replied',c.replied],['done',c.done],['uninterested',c.uninterested],['contacted',partners.length-c.not]].forEach(([i,v])=>{if($(i))$(i).textContent=v});if(!$('cards'))return;let q=($('search')?.value||'').trim().toLowerCase(),a=partners.filter(x=>[x.name,x.email,x.phone,x.type,x.status,x.contactPerson].join(' ').toLowerCase().includes(q));let f=document.body.dataset.filter||'all';if(f==='contacted')a=a.filter(x=>x.status!=='لم يتم التواصل');if(f==='not-contacted')a=a.filter(x=>x.status==='لم يتم التواصل');$('cards').innerHTML=a.length?a.map(card).join(''):'<div class="empty">لا توجد بيانات في هذه الصفحة.</div>'}
function card(x){return `<article class="partner"><div class="partner-top"><div><div class="meta">${esc(x.type||'جهة شراكة')}</div><h3>${esc(x.name)}</h3></div><div class="icon">▦</div></div><div class="meta">${esc(x.email||'لا يوجد بريد')}<br>${esc(x.phone||'لا يوجد رقم')}</div><span class="badge">${esc(x.status)}</span>${x.nextFollowup?` <span class="chip">متابعة: ${esc(x.nextFollowup)}</span>`:''}<div class="actions">${x.status==='لم يتم التواصل'?`<button class="btn btn-main" onclick="contactPartner(${x.id})">تواصل</button>`:`<button class="btn btn-soft" onclick="quickStatus(${x.id})">تحديث الحالة</button>`}<a class="btn btn-soft backlink" href="company.html?id=${x.id}">التفاصيل</a><button class="btn btn-danger" onclick="removePartner(${x.id})">حذف</button></div></article>`}
function contactPartner(id){active=partners.find(x=>x.id===id);if(!active)return;$('targetName').textContent=active.name;$('to').value=active.email||active.phone||'';$('subject').value='مقترح شراكة وتعاون مع مركز محترف';$('body').value='السلام عليكم ورحمة الله وبركاته،\n\nنسعد في مركز محترف بالتواصل معكم لبحث فرص الشراكة والتعاون المشترك.\n\nوتفضلوا بقبول خالص التحية والتقدير.\nمركز محترف';$('mailModal').classList.add('show')}
function markContacted(){if(!active)return;active.status='بانتظار الرد';active.contactedAt=nowISO();active.lastSubject=$('subject')?.value||'';active.lastMessage=$('body')?.value||'';hist(active,'تواصل','تم تسجيل التواصل الأول وتحويل الحالة إلى بانتظار الرد');persist();closeMail();render();alert('تم تسجيل التواصل ونقل الجهة إلى بانتظار الرد')}
function quickStatus(id){let x=partners.find(a=>a.id===id);let v=prompt('الحالة الجديدة: تم الرد / إعادة تواصل / غير مهتم / تم الاتفاق / بانتظار الرد',x.status);if(!v)return;let allowed=['تم الرد','إعادة تواصل','غير مهتم','تم الاتفاق','بانتظار الرد'];if(!allowed.includes(v))return alert('الحالة غير معتمدة');x.status=v;hist(x,'حالة','تم تغيير الحالة إلى '+v);persist();render()}
function removePartner(id){if(confirm('هل تريد حذف هذه الجهة؟')){partners=partners.filter(x=>x.id!==id);save()}} function closeMail(){if($('mailModal'))$('mailModal').classList.remove('show')} function copyMessage(){navigator.clipboard.writeText(`إلى: ${$('to').value}\nالموضوع: ${$('subject').value}\n\n${$('body').value}`)}
function loadCompany(){let id=Number(new URLSearchParams(location.search).get('id')),x=partners.find(a=>a.id===id);if(!x){$('companyView').innerHTML='<div class="empty">الجهة غير موجودة</div>';return}active=x;$('companyView').innerHTML=`<div class="detail-grid"><div class="info-card"><h2>${esc(x.name)}</h2><div class="field"><label>المسؤول</label><input id="cp" value="${esc(x.contactPerson||'')}"></div><div class="field"><label>المنصب</label><input id="pos" value="${esc(x.position||'')}"></div><div class="field"><label>البريد</label><input id="em" value="${esc(x.email||'')}"></div><div class="field"><label>الجوال</label><input id="ph" value="${esc(x.phone||'')}"></div><div class="field"><label>الموقع الإلكتروني</label><input id="web" value="${esc(x.website||'')}"></div><div class="field"><label>نوع الشراكة</label><input id="typ" value="${esc(x.type||'')}"></div><div class="field"><label>الحالة</label><select id="st">${['لم يتم التواصل','بانتظار الرد','تم الرد','إعادة تواصل','غير مهتم','تم الاتفاق'].map(v=>`<option ${x.status===v?'selected':''}>${v}</option>`).join('')}</select></div><div class="field"><label>موعد المتابعة القادمة</label><input id="fu" type="date" value="${esc(x.nextFollowup||'')}"></div><div class="field"><label>الملاحظات</label><textarea id="nt">${esc(x.notes||'')}</textarea></div><button class="btn btn-main" onclick="saveCompany()">حفظ التعديلات</button></div><div class="info-card"><h2>سجل التواصل</h2><div class="field"><label>إضافة ملاحظة للسجل</label><textarea id="logtxt"></textarea></div><button class="btn btn-soft" onclick="addLog()">إضافة للسجل</button><div class="timeline" style="margin-top:24px">${(x.history||[]).map(h=>`<div class="event"><b>${esc(h.type)}</b><div>${esc(h.text)}</div><small>${new Date(h.at).toLocaleString('ar-SA')}</small></div>`).join('')||'<div class="meta">لا يوجد سجل بعد.</div>'}</div></div></div>`}
function saveCompany(){let x=active,old=x.status;x.contactPerson=$('cp').value;x.position=$('pos').value;x.email=$('em').value;x.phone=$('ph').value;x.website=$('web').value;x.type=$('typ').value;x.status=$('st').value;x.nextFollowup=$('fu').value;x.notes=$('nt').value;if(old!==x.status)hist(x,'حالة','تم تغيير الحالة من '+old+' إلى '+x.status);hist(x,'تعديل','تم تحديث بيانات الجهة');persist();loadCompany();alert('تم الحفظ')}
function addLog(){let t=$('logtxt').value.trim();if(!t)return;hist(active,'متابعة',t);persist();loadCompany()}
function renderFollowups(){let box=$('followupRows');if(!box)return;let today=new Date().toISOString().slice(0,10);let a=partners.filter(x=>x.nextFollowup).sort((a,b)=>a.nextFollowup.localeCompare(b.nextFollowup));box.innerHTML=a.length?a.map(x=>`<tr><td><a href="company.html?id=${x.id}">${esc(x.name)}</a></td><td>${esc(x.status)}</td><td><span class="chip ${x.nextFollowup<today?'overdue':x.nextFollowup===today?'today':''}">${esc(x.nextFollowup)}</span></td><td>${esc(x.phone||x.email||'—')}</td></tr>`).join(''):'<tr><td colspan="4">لا توجد متابعات مجدولة.</td></tr>'}
document.addEventListener('DOMContentLoaded',()=>{render();if($('companyView'))loadCompany();renderFollowups()});