let partners=JSON.parse(localStorage.getItem('mohteref_partners')||'[]'),active=null;
const $=id=>document.getElementById(id);
function toggleMenu(force){let s=$('sidebar'),ov=$('overlay');if(!s)return;let o=force===undefined?!s.classList.contains('open'):force;s.classList.toggle('open',o);if(ov)ov.classList.toggle('show',o)}
function esc(s){return String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function save(){localStorage.setItem('mohteref_partners',JSON.stringify(partners));render()}
function addPartner(){let n=$('name').value.trim(),e=$('email').value.trim(),p=$('phone').value.trim();if(!n){alert('أدخل اسم الشركة أو الجهة');return}partners.unshift({id:Date.now(),name:n,email:e,phone:p,type:$('type').value.trim(),status:$('pstatus').value,notes:$('notes').value.trim()});localStorage.setItem('mohteref_partners',JSON.stringify(partners));alert('تم حفظ بيانات الشركة');location.href='companies.html'}
function render(){if($('total')){$('total').textContent=partners.length;$('contacted').textContent=partners.filter(x=>x.status!=='لم يتم التواصل').length;$('notContacted').textContent=partners.filter(x=>x.status==='لم يتم التواصل').length;$('done').textContent=partners.filter(x=>x.status==='شراكة مكتملة').length}if(!$('cards'))return;let q=($('search')?.value||'').trim().toLowerCase(),a=partners.filter(x=>[x.name,x.email,x.phone,x.type,x.status].join(' ').toLowerCase().includes(q));let f=document.body.dataset.filter||'all';if(f==='contacted')a=a.filter(x=>x.status!=='لم يتم التواصل');if(f==='not-contacted')a=a.filter(x=>x.status==='لم يتم التواصل');$('cards').innerHTML=a.length?a.map(x=>`<article class="partner"><div class="partner-top"><div><div class="meta">${esc(x.type||'جهة شراكة')}</div><h3>${esc(x.name)}</h3></div><div class="icon">▦</div></div><div class="meta">${esc(x.email||'لا يوجد بريد')}<br>${esc(x.phone||'لا يوجد رقم')}</div><span class="badge">${esc(x.status)}</span>${x.notes?`<div class="meta" style="margin-top:10px">${esc(x.notes)}</div>`:''}<div class="actions"><button class="btn btn-main" onclick="compose(${x.id})" ${x.email?'':'disabled'}>مراسلة</button><button class="btn btn-soft" onclick="changeStatus(${x.id})">تحديث الحالة</button><button class="btn btn-danger" onclick="removePartner(${x.id})">حذف</button></div></article>`).join(''):'<div class="empty">لا توجد بيانات في هذه الصفحة.</div>'}
function changeStatus(id){let x=partners.find(p=>p.id===id),opts=['لم يتم التواصل','تم التواصل','بانتظار الرد','شراكة مكتملة','غير مهتم'],v=prompt('اكتب حالة التواصل:\n'+opts.join(' / '),x.status);if(v&&opts.includes(v)){x.status=v;save()}}
function removePartner(id){if(confirm('هل تريد حذف هذه الجهة؟')){partners=partners.filter(x=>x.id!==id);save()}}
function compose(id){active=partners.find(x=>x.id===id);$('targetName').textContent=active.name;$('to').value=active.email;$('subject').value='مقترح شراكة وتعاون مع مركز محترف';$('body').value=`السلام عليكم ورحمة الله وبركاته،\n\nنسعد في مركز محترف بالتواصل معكم لبحث فرص الشراكة والتعاون المشترك.\n\nوتفضلوا بقبول خالص التحية والتقدير.\nمركز محترف`;$('sendStatus').textContent='';$('mailModal').classList.add('show')}
function closeMail(){$('mailModal').classList.remove('show')}function prepareSend(){if(!$('subject').value.trim()||!$('body').value.trim()){$('sendStatus').className='status warn';$('sendStatus').textContent='اكتب الموضوع والرسالة أولاً.';return}$('sendStatus').className='status warn';$('sendStatus').textContent='جاهز للإرسال؛ يتبقى ربط Gmail API لتفعيل الإرسال المباشر.'}function copyMessage(){navigator.clipboard.writeText(`إلى: ${$('to').value}\nالموضوع: ${$('subject').value}\n\n${$('body').value}`);$('sendStatus').className='status ok';$('sendStatus').textContent='تم نسخ الرسالة.'}
document.addEventListener('DOMContentLoaded',render);